"""updated the mOdels for ev_data, vehicles, 

Revision ID: 4873ba6450dc
Revises: 9ec6f86531f1
Create Date: 2026-06-10 23:56:10.119434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4873ba6450dc'
down_revision: Union[str, Sequence[str], None] = '9ec6f86531f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ev_data', sa.Column('maintenance_type', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('nickname', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('battery_capacity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'battery_capacity')
    op.drop_column('vehicles', 'nickname')
    op.drop_column('ev_data', 'maintenance_type')
    # ### end Alembic commands ###
