"""add user fk to vehicles

Revision ID: 7a6b7e413d36
Revises: 001e1b7ae90f
Create Date: 2026-06-05 23:46:44.295155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a6b7e413d36'
down_revision: Union[str, Sequence[str], None] = '001e1b7ae90f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vehicles', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'user_id')
    # ### end Alembic commands ###
