"""initial_schema

Revision ID: 9744753fb04f
Revises: 
Create Date: 2026-06-21 01:58:41.574614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9744753fb04f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hash_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vehicles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('battery_capacity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('distance_unit', sa.String(), nullable=True),
    sa.Column('temperature_unit', sa.String(), nullable=True),
    sa.Column('default_vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['default_vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_app_settings_id'), 'app_settings', ['id'], unique=False)
    op.create_table('ev_data',
    sa.Column('data_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('soc', sa.Float(), nullable=True),
    sa.Column('soh', sa.Float(), nullable=True),
    sa.Column('battery_voltage', sa.Float(), nullable=True),
    sa.Column('battery_current', sa.Float(), nullable=True),
    sa.Column('battery_temperature', sa.Float(), nullable=True),
    sa.Column('charge_cycles', sa.Integer(), nullable=True),
    sa.Column('motor_temperature', sa.Float(), nullable=True),
    sa.Column('motor_vibration', sa.Float(), nullable=True),
    sa.Column('power_consumption', sa.Float(), nullable=True),
    sa.Column('ambient_temperature', sa.Float(), nullable=True),
    sa.Column('load_weight', sa.Float(), nullable=True),
    sa.Column('driving_speed', sa.Float(), nullable=True),
    sa.Column('distance_traveled', sa.Float(), nullable=True),
    sa.Column('motor_torque', sa.Float(), nullable=True),
    sa.Column('motor_rpm', sa.Float(), nullable=True),
    sa.Column('brake_pad_wear', sa.Float(), nullable=True),
    sa.Column('brake_pressure', sa.Float(), nullable=True),
    sa.Column('reg_brake_efficiency', sa.Float(), nullable=True),
    sa.Column('tire_pressure', sa.Float(), nullable=True),
    sa.Column('tire_temperature', sa.Float(), nullable=True),
    sa.Column('suspension_load', sa.Float(), nullable=True),
    sa.Column('ambient_humidity', sa.Float(), nullable=True),
    sa.Column('idle_time', sa.Float(), nullable=True),
    sa.Column('route_roughness', sa.Float(), nullable=True),
    sa.Column('maintenance_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('data_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ev_data')
    op.drop_index(op.f('ix_app_settings_id'), table_name='app_settings')
    op.drop_table('app_settings')
    op.drop_table('vehicles')
    op.drop_table('users')
    # ### end Alembic commands ###
