"""added extra column to the EVDataModel

Revision ID: 9ec6f86531f1
Revises: 7a6b7e413d36
Create Date: 2026-06-10 00:43:36.309555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ec6f86531f1'
down_revision: Union[str, Sequence[str], None] = '7a6b7e413d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ev_data', sa.Column('motor_torque', sa.Float(), nullable=True))
    op.add_column('ev_data', sa.Column('motor_rpm', sa.Float(), nullable=True))
    op.add_column('ev_data', sa.Column('brake_pad_wear', sa.Float(), nullable=True))
    op.add_column('ev_data', sa.Column('brake_pressure', sa.Float(), nullable=True))
    op.add_column('ev_data', sa.Column('reg_brake_efficiency', sa.Float(), nullable=True))
    op.add_column('ev_data', sa.Column('tire_pressure', sa.Float(), nullable=True))
    op.add_column('ev_data', sa.Column('tire_temperature', sa.Float(), nullable=True))
    op.add_column('ev_data', sa.Column('suspension_load', sa.Float(), nullable=True))
    op.add_column('ev_data', sa.Column('ambient_humidity', sa.Float(), nullable=True))
    op.add_column('ev_data', sa.Column('idle_time', sa.Float(), nullable=True))
    op.add_column('ev_data', sa.Column('route_roughness', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ev_data', 'route_roughness')
    op.drop_column('ev_data', 'idle_time')
    op.drop_column('ev_data', 'ambient_humidity')
    op.drop_column('ev_data', 'suspension_load')
    op.drop_column('ev_data', 'tire_temperature')
    op.drop_column('ev_data', 'tire_pressure')
    op.drop_column('ev_data', 'reg_brake_efficiency')
    op.drop_column('ev_data', 'brake_pressure')
    op.drop_column('ev_data', 'brake_pad_wear')
    op.drop_column('ev_data', 'motor_rpm')
    op.drop_column('ev_data', 'motor_torque')
    # ### end Alembic commands ###
